import { ExamData } from '../types';

export const sscChsl: ExamData = {
  rules: {
    id: 'ssc_chsl',
    name: 'SSC CHSL TYPING',
    // Using the exact same SSC logo here
    logo: '/media/ssc-logo.png',
    duration: 10 * 60, // 10 minutes
    allowBackspace: true,
    highlightCurrentWord: false,
    showLiveErrors: false,
    targetWpm: 35, // LDC/JSA requirement
    description: "Candidates who want to do English Typing will be required to type at a speed of 35 words per minute (10,500 key depressions/hour) and candidates who want to do Hindi typing will be typed at 30 words per minute (9,000 key depressions/hour) within 10 minutes (15 minutes for PwD candidates). During application, you are supposed to choose either English or Hindi as your typing language. Nothing to be changed afterwards. The text passage to be typed will be on the screen in the test. You have to type without stopping in 10 minutes (15 minutes in case of PwD)."
  },
  passages: [
    {
      id: 'ssc-chsl-pytt-1',
      title: 'SSC CHSL PYTT - 1',
      difficulty: 'PYTT',
      text: "Sir, I would like to state that the Budget is only an annual financial statement anticipating the total revenues and the total expenditure of the Government. It can try to solve the existing problems in the country and also carry forward the process of growth that has been achieved so far. A Budget has to be implemented in a number of parameters. We have to look at the parameters and then judge the Budget. After looking from all these angles, I would say that the Union Budget is a good Budget, Among other things, the most salient aspect of this Budget is that it carries the mandate given in the Common Minimum Programme. The Budget has to carry forward all the plans and schemes that have been given in the Plan and it has to serve the goals of not only growth but also inclusive growth. Only growth can relieve India from the clutches of poverty and unemployment. No magic remedies are available except that we have to promote sustained growth in agriculture, sustained growth in industry and sustained growth in infrastructure. Without that it is not possible, and that would be possible only with generous fundings. Sir, I rise to support the General Budget which has been presented by the hon. Finance Minister. He deserved our appreciation for presenting the growth- oriented Budget. As you know, this is the fifth Budget of the hon. Finance Minister as well as of this Government. In my considered view, this is the finest of all the Budgets which has been presented by this Government. Some hon. Members were finding fault with the Government for not eradicating poverty and not reducing inequalities in this country. These are all old problems and cannot be tackled by Budget. A budget expresses intended expenditures along with proposals."
    },
    {
      id: 'ssc-chsl-pytt-2',
      title: 'SSC CHSL PYTT - 2',
      difficulty: 'PYTT',
      text: "Money stashed abroad is not always the money, which has been evaded from payment of taxes. Drug lords, terrorists groups, gangsters all over the world, along with International Syndicates also keep their money in safe heavens, where they can lay their hands on it in times of need for their operational purposes. There is no mechanism with the Government to determine and say with cent per cent surety that the money hoarded abroad is only the one that has been evaded from payment of taxes and not the other crime linked cash. The Revenue Department and other agencies of the Government like the RAW and State Trading Organisations have their offices abroad. There is no common mandate to them to report any suspicious transactions by the Indians either visiting or staying abroad. The stark truth is that the black money is the result of high level corruption prevailing in our country. The schemes meant for the poor, even as per the Government reports, are not implemented and the money siphoned off. Even laws permit every criminal whether in jail or on bail to hide their names and crimes and create false alibis. But, here the Government is creating alibis for those people whose names have been received and disclosed as the persons who are having cash, which is got illegally and is not from any known legal sources. They have stashed this cash in safe tax heavens abroad. Even the Supreme Court, the Apex Court of India, says that nothing moves without bribery in India. A good and alert cop even on a tourist visa can spot Indians roaming about and visiting these safe tax heavens on Swiss banks. The rest of the job of tracing the flight of black money from India can be done locally provided the Government has the will. So far, the Government has been making excuses"
    },
    {
      id: 'ssc-chsl-pytt-3',
      title: 'SSC CHSL PYTT - 3',
      difficulty: 'PYTT',
      text: "Is positive thinking an inherent characteristic of a person or can it (69) be developed in one's psyche? The opinions differ in answering this vital question. Some people believe that it can be inherited from parents, and cannot be developed. Others believe that like other qualities it can be developed with proper practice and guidance. Still some others hold the opinion that it is hereditary to some extent but can be acquired to some degree. There is also a section of people, who believe that all depends on circumstances or luck. We need to adopt a scientific approach to find an answer to the above question. No one can get success every time even after making efforts, nor can one fail constantly. Moreover, success has different meaning for different people. For some students, getting 60 per cent marks is success, for others it may not be sufficient. In a competitive examination, success means getting selected, whatever the percentage of marks. As for inheritance theory, since positive attitude is not a physical feature but a mental faculty, it cannot be purely hereditary. It can be developed. Moreover, parents play a major role in developing this quality of a child. A child, who watches his parents working hard, having faith in success through their words, behaviour and body language, is likely to develop a similar attitude. The children of short-tempered, over-cautious and nervous parents may assume similar characteristics when they grow up. Psychologists, therefore, prescribe a code of conduct for parents' behaviour in front of their children. They must exude confidence, self-belief and hope, especially in difficult situation, so that the children emulate these qualities. They must be taught the importance of being positive"
    },
    {
      id: 'ssc-chsl-pytt-4',
      title: 'SSC CHSL PYTT - 4',
      difficulty: 'PYTT',
      text: "Stretching specific tendon or muscle can improve the elasticity of muscles, which in turn helps in achieving a comfortable muscle tone. There are several benefits of regular stretching, and it should be an integral part of every workout program. It not only helps increase your flexibility, which is an important part of fitness, but it can also improve your posture, body aches, reduce stress, and much more. One of the benefits of regular stretching is that it enhances flexibility. Being flexible has its own advantages, as it not only improves your day to day activities, but can also help delay the reduced mobility that comes with aging. Stretching 9on a regular basis can help increase your range of motion. You can either go for static or dynamic stretching as they both are effective when it comes to the increasing range of motion. According to the studies, proprioceptive neuromuscular facilitation or PNF type of stretching is more effective for immediate results. Regular stretching can not only help heal an existing back injury but can also prevent future back pain by reducing your risk for muscle strain and strengthening your back muscles. All the people who regularly go to the gym know how helpful stretching can be. Performing dynamic stretches prior to exercise in the gym can help prepare your muscles. Not the only gym, but it can also help you improve your performance in dance or an athletic event. It is only natural that your muscles get tense when you experience physical or emotional stress. This is because the tightening of your muscles is the response of the body towards stress. All you need to do is focus on the areas of your body where you feel the stress, such as your neck, shoulders, etc. and stretch those parts of your body."
    },
    {
      id: 'ssc-chsl-pytt-5',
      title: 'SSC CHSL PYTT - 5',
      difficulty: 'PYTT',
      text: "After the recent merger of two former public sector banks, Vijaya Bank and Dena Bank into Bank of Baroda, the BoB is now the second largest public sector bank of the country. It now has 9,500 branches and 85,000 employees with a business mix of more than Rs.15 lakh crore. It is reported that the BoB will protect the interests of all the employees and customers. It is also stated that the BoB will focus on the operational costs, customer satisfaction and will try to maximize profit. Historically, the experience of bank mergers or amalgamations in India is mixed. In most cases, improvement was not much. Even the recent merger of associated banks of the State Bank of India into the SBI has not been very satisfactory. A bank has to do its business in a complex environment where domestic and international economic factors influence it. Even political interference is not absent. Now, private and public sector banks are doing business in a common market. Practically, these two categories do not do their jobs in the same way. Therefore, the BOB faces several challenges in the days to come. There are many big banks that have either liquidated or face great financial trouble. Amalgamation cannot be an end in itself, Some of the challenges are internal to the bank and same are external to it Some of the internal challenges, as has been pointed out, are first, Dena Bank and BoB has a similar background and culture, which can be takes as the old Gujarati culture. But Vijaya Bank came from a different milieu. So, some cultural shock in human resources development is expected Second, Dena Bank and Vijaya Bank had a huge baggage of NPA. Third, Dena Bank and Vijaya Bank had a large exposer to trade finance. In this sector, asset recovery is more difficult."
    },
    {
      id: 'ssc-chsl-pytt-6',
      title: 'SSC CHSL PYTT - 6',
      difficulty: 'PYTT',
      text: "Cyber technology has also changed the way we do financial trade. More and more people are using online platforms for shopping, transferring money and other financial dealings. Moreover, efforts are being made to facilitate financial education in schools in order to make students ready for future. In view of Increasing cyber crimes related to financial frauds, the ubsequent chapters provide an overview to children on cyber threats elated to online financial transactions and how to safeguard ourselves against such threats. The subsequent chapters of the report cover cyber threats related to social networking and how to safeguard against such threats. The report will help students and other users to learn about cyber threats and ways in which they can protect themselves. As a change agent, students and their mentors are expected to share their learning with their peers and parents and contribute in making cyber space safer. Nowadays, internet, computers, smart phones and other communication technology devices have become an integral part of our life. Imagine how much time we spend each day on these smart devices. We have made internet communication mediums like emails, Whatsapp, Facebook, etc. part and parcel of our everyday activities. But most of us are unaware of cyber safety and security features to safeguard ourselves. Do you know that whatever information or personal details are shared on internet stay online forever as it is extremely difficult to delete the information completely? Cyber are offences that may be ommitted against individuals, firms or institutions by using computers, internet or mobile technology. Criminals in cyber space use platforms such as social networking sites, e-mails, chat rooms, pirated software"
    },
    {
      id: 'ssc-chsl-pytt-7',
      title: 'SSC CHSL PYTT - 7',
      difficulty: 'PYTT',
      text: "Todine fortification is what most countries rely on to encourage adequate dietary intake. In more than seventy countries that iodize salt generally serves as the major source of iodine intake. One fourth of a teaspoon of iodized salts has about hundred micrograms of iodine. Note that the salt used in processed foods, which is the major source of salt for most Americans typically does not contain iodine. If salt used in a processed food contains iodine, it will be listed in the ingredients list of that food. Focus on decreasing the amount of salt consumed from processed foods and get your sodium from iodized salt. Seaweed, saltwater fish and seafood are natural sources of dietary iodine. Dairy products also supply iodine in the diet at varying levels. During lactation, the breast concentrates iodine in milk so breastmilk tends be a good source of iodine as long as the iodine intake of a mother is adequate. Plants grown in iodine rich soil are also good sources. However, this is not a reliable source of iodine since there is no way of knowing whether produce purchased in grocery stores is grown in iodine rich soil or not. Iodized salt usually adds less than about three hundred micrograms iodine daily to the diet. Most multivitamin mineral supplements contain 150 micrograms of iodine. With the safe upper limit of daily iodine intake for adults set at 1,100 micrograms by the IOM it is unlikely to hit an excess amount when including a multivitamin and including natural sources of dietary iodine. The trend of eating less table salt, dairy and bread has some experts concerned that iodine deficiency could be on the rise again. Eating a healthy, balanced diet that includes iodine rich foods and iodized salt is key to good health."
    },
    {
      id: 'ssc-chsl-pytt-8',
      title: 'SSC CHSL PYTT - 8',
      difficulty: 'PYTT',
      text: "Discipline is one of the most significant personality traits in life. Saints and monks who meditate also first practice the art of discipline. A person who is well disciplined is on track and has orderliness in life. Discipline is the bridge between goals and accomplishment hence it is the key to success. Discipline in student life attracts all the right things and because of this students gain success in each field of their life. The discipline is always catered as a guide to focus on their goals. A disciplined student focuses on their goals and their mind does not wonder about other useless things. A well disciplined child has a positive attitude in life. A well disciplined student is focused. Discipline teaches students to be concentrated and motivated toward their studies as well as other areas of their life. Someone with the strong goals is more focused and always keeps his job on time in daily life. It helps the student to remain calm and composed. This helps them to maintain the focus and to keep moving on with the problems. Meanwhile a student who is not disciplined finds it hard to concentrate on their studies. A well disciplined student is also active. They know what is best for them. An active student follows disciplined habits such as regular exercise having good food and rest well. Discipline helps the student to maintain a proper schedule for everything which includes time for all the subjects. A disciplined student has good self control. A well disciplined person always remains happy by relieving stress in the face of tension during examinations or day to day work. Proper discipline helps students build a positive attitude towards everything. This helps them to improve their performance slowly and steadily."
    },
    {
      id: 'ssc-chsl-pytt-9',
      title: 'SSC CHSL PYTT - 9',
      difficulty: 'PYTT',
      text: "India wants to be seen as a sports destination of repute and the choice of Ahmedabad is strategic too. Exactly two decades after hosting its maiden Commonwealth Games CWG, India will welcome the quadrennial extravaganza centenary edition to its shores in 2030. The move is another unmistakable sign that India wants to be seen as a sports destination of repute. The choice of Ahmedabad as the host city is strategic too, for India has submitted the Letter of Intent to hold the 2036 Olympics with Ahmedabad as the front-runner. However, while the Olympics retains its allure and grandeur, the CWG has been beset with difficulties. Once signifying the imperial unity of the British empire, the CWG is struggling for relevance in the post-colonial world. Successive host cities have dropped out citing rising costs Birmingham replaced Durban in 2022; Glasgow has come to the rescue for 2026 after the Australian State of Victoria withdrew, and Ahmedabad has stepped in for the Canadian province of Alberta. Not so long ago, India itself was cold to the competition, with the then Indian Olympic Association president Narinder Batra, in 2019, calling it \"sub-standard\" albeit in his personal capacity and strongly pitching for India's withdrawal. Also, when New Delhi conducted the Games in 2010, there were allegations galore of large-scale corruption and incompetence. So, what merit does India see now? First, it is an important soft-power medium. Second, the nation's sporting aspirations have grown manifold, and though performances by its sportspersons have not kept pace, there is a genuine push toward diversifying on-field excellence and going beyond just cricket. India has world-class heroes such as double-Olympic medallist javelin thrower Neeraj Chopra"
    }
  ]
};