import { ExamData } from '../types';

export const sscCgl: ExamData = {
  rules: {
    id: 'ssc_cgl',
    name: 'SSC CGL TYPING',
    // Pointing to your local image in the public/media folder
    logo: '/media/ssc-logo.png',
    duration: 15 * 60, // 15 minutes
    allowBackspace: true,
    highlightCurrentWord: false, 
    showLiveErrors: false,
    targetWpm: 27, 
    description: "Key Depression: The skill test will involve passages with approximately 2000 key depressions in the text. Time Required: Candidates will have 15 minutes to complete the typing test. DEST will be mandatory for all the posts; however, it will be qualifying in nature. For English Typing: 35 Words Per Minute (WPM) and for Hindi Typing: 30 Words Per Minute (WPM)."
  },
  passages: [
    {
      id: 'ssc-cgl-pytt-1',
      title: 'SSC CGL PYTT - 1',
      difficulty: 'PYTT',
      text: "The State can promote the arts by providing a helpful environment. The environment for the arts in the immediate past in India has not been very helpful. Firstly before Independence all our efforts were directed to the political field. Secondly, during the long period of British Rule in India, we thought far too much of foreign models. That trend was good to the extent it supplied new impulses but when it was overdone, the arts became imitative, losing their creative tendencies. An art cannot be imitated, it has to come out of people's lives and urges. India is rich in artistic forms. But they have suffered from a long period of stagnation and repetition. What more wonderful things can we have than some of the old specimens of Indian architecture? They are amazing in their strength and beauty, which we miss in our later forms of architecture which are all repetition. We lost that grand style in architecture, which we see in the other countries, where our artisans went in number of other places. Now, take the example of classical dances in India. It is a well-known fact that for various reasons these dances began to die off. It almost was thought that it was improper and immoral to dance. Voices were raised against our dance forms and they nearly died. Fortunately, there were some persons and groups who kept these dances alive and we see how when those restrictions were removed, they have begun to flourish in India. This is true not only of our classical dances but even more so of the folk dances of India also which are really wonderful in their variety. We have these folk dances in Kerala, as in other regions, but the tribal areas are richest in the folk dances. The Republic Day celebration in Delhi provides an occasion for presenting the folk dances from every part of India. An appreciative environment is helping the dances of India to grow. Similarly, I am told that considerable advance is being made all over India in the musical domain. I am not quite sure where we are."
    },
    {
      id: 'ssc-cgl-pytt-2',
      title: 'SSC CGL PYTT - 2',
      difficulty: 'PYTT',
      text: "The Bill, as passed by the Lok Sabha, is already with the hon. Members The Select Committee earlier went exhaustively into the various provisions of the original Bill and also recorded evidence from some of the representatives of the industry. The various recommendations of the select committee has been incorporated in the Bill. In addition, the wishes expressed by some of the Members of the Lok Sabha have been incorporated in the Bill. The difficulties of small growers have been apprecrated and the major portion of the acreage of rubber cultivation is held by the small growers. Proper representation to these small producers of rubber will be given. The labour representatives in the Board have been increased from three to four. The labour representatives will be selected from out of the panel of names submitted by the respective associations an important provision has been made in the Bill to enable the Board to take steps to secure better working conditions for workers engaged in the rubber industry. The present production, of rubber is about twenty thousand tons a year, the demand is increasing every year, while the supply is not keeping pace with the demand. It is proposed to fill up the gap over the short period by importing rubber. The Bill, when passed would enable the Board to import rubber and a provision has been made as to how any profits that are made out of this import of rubber should be utilised. To increase the, production of rubber, it is proposed to take up the development scheme. The details of which are being worked out. It appears that at present the small grower is at a great disadvantage, as far as the marketing of his rubber is concerned. This problem is rather difficult to solve However, provisions have been made for the Rubber Board to take up marketing of rubber also. It is hoped that the new Board will be able to tackle the problem of the small grower of rubber industry successfully. The Rubber industry has established itself as a major industry in India. India ranks high in natural rubber production"
    },
    {
      id: 'ssc-cgl-pytt-3',
      title: 'SSC CGL PYTT - 3',
      difficulty: 'PYTT',
      text: "Under the National Drinking Water Mission, the guinea worm problem which is prevalent in only six States will now be eliminated by the end of the current year. Similarly, the Central Government has taken several steps to remove the excess quantity of fluoride from drinking water. Alternative sources of clean drinking water and equipment to remove fluoride will be made available to the affected villages. For both the works, a special provision to provide funds to the States is being made. Public awakening campaign is being launched in this regard. The Government has taken the decision to open laboratories at all the places for the qualitative testing of drinking water. I would also like to point out that the constructed amenities provided for the disposal of dirt and dirty water are comparatively very inadequate. This issue will be taken up for discussion at an early date in the National Seminar and the policy will undergo change. I would like to mention that the World Bank and many countries of the world are: extending their assistance for the implementation of these two programmes. The programme started to make available drinking water in villages through Rajiv Gandhi National Drinking Water Mission, is the biggest in the world and has become a model for other developing countries. In order to have systematic agricultural development and to maintain it, an effective system is essential for marketing of agricultural products so that the interests of producers and consumers may be safeguarded. A model Act has been circulated to the States in order to make uniformity in the regulation and management of markets. In order to provide basic infrastructure facilities for these markets under a Centrally-sponsored programme, the committees of the trade centers are given monetary assistance to the markets through the State Government. Now, both the programmes for the development of markets and construction of village godowns have been entrusted to the State Governments."
    },
    {
      id: 'ssc-cgl-pytt-4',
      title: 'SSC CGL PYTT - 4',
      difficulty: 'PYTT',
      text: "Many marine organisms rely on their ability to hear for their survival. Sound is a highly efficient means of communication underwater and is the primary way that many marine species gather and understand information about their environment. Many aquatic animals use sound to find prey locate mates and offspring avoid predators guide their navigation and locate habitat as well as to listen and communicate with each other. Oceans are full of sound. Waves, earthquakes and icebergs all contribute to the underwater soundscape. But so do human activities and this can be a problem for marine life as it can seriously affect their physiology behaviour, reproduction and even survival. Being able to produce and detect sound in an environment where light penetrates only a few hundred metres is crucial for animals to communicate, feed, avoid predators and navigate vast underwater habitats. Large whales generate low frequency communication calls that can travel thousands of kilometres. While the snapping shrimp, native to the western Atlantic, can produce a loud snapping sound capable of stunning and killing its prey. The noise generated by humans changes the natural acoustic environment of our oceans and our capacity to produce it is increasing. Noise is often the unintentional by product of transport infrastructure development and industry. Yet noise can also be produced deliberately. Many navies use sonar system to detect ships and submarines while geologists survey the seabed for oil and gas using seismic airguns. The noise produced by an airgun can exceed 200 decibels louder than a gunshot at a range of one metre. Sound travels further and four times faster in water than in air at a speed of almost 1500 metres per second. The noise produced by humans can therefore spread considerable distances underwater. These sounds can be relatively constant such as the noise produced by the engine of a ship and propeller or sudden and acute in the case of naval sonar and seismic airguns."
    },
    {
      id: 'ssc-cgl-pytt-5',
      title: 'SSC CGL PYTT - 5',
      difficulty: 'PYTT',
      text: "As the House knows, the Prime Minister sent out a circular to all the States a few years ago requesting that the portfolio of agriculture in the States should not be neglected; it should be entrusted to an important Minister. I think the National Development Council considered this question and they said that as far as possible, the Chief Ministers in the States should handle the portfolio themselves. And then, they have started a Food Production Board in the Cabinet itself at the Centre, and the National Development Council has decide that an agricultural production board should be started in each State with the Chief Minister as the Chairman. They have started an agricultural machinery board for supplying machinery. They have taken many steps in addition to the normal measures. The Government has been doing their very best in this regard. But with all that, it has not kept up with the targets fixed, unless earnest and vigorous attempts are made. I wish to throw out my own suggestions in this regard. They may not be very pleasant but I wish to be excused because I am speaking from experience. Madam, the first thing is that so far as the producing agency is concerned, its voluntary interest and its enthusiasm must be won. For instance, in industrial labour relations, we got out of the way to invite labour and give it even participation in the management and to do everything for labour. This is just to see that industrial relations are good and the industrial output will be increasing day by day. Should we not show some consideration for this producing agency, namely, the farmer? Mr. Thomas has shown how agricultural products, even at these increased prices, are not paying to the agriculturist. He has shown that very correctly, and everyone who has intimate connection with agriculture at least will agree to that, and if at all anything, that is an under-estimate, not an over-estimate. When that is so, how can we expect the farmer to produce unless he is enthused?"
    },
    {
      id: 'ssc-cgl-pytt-6',
      title: 'SSC CGL PYTT - 6',
      difficulty: 'PYTT',
      text: "Sir, the Press Council Second Amendment Bill was introduced by me in the last session, as I submitted in my statement which I laid on the Table of the House. I request the House to consider the Second Amendment because an Ordinance had to be issued since the life of the Council was expiring. Since the life of the present council was expiring, we had to issue the Ordinance. At this stage, I do not think have much to say because it is a very simple Bill. It is only trying to extend the life of the Press Council till the end of the year. If we are able to finalize the formation of the Press Council earlier, then, of course, the present term would expire earlier. You will recall, I had said in the course of the last debate that a Committee of Members of Parliament has been working for the drafting of the second Bill, which is likely to come up before the end of this session. The Committee has been sitting and they have been able to come to their conclusions more or less. It is now in the drafting stage and I hope it will be possible for me to bring the Bill before the House soon, 1 would not like to go into the merits and demerits of the new Bill at this stage. Would only say that it is a very simple Bill extending the life of the present Council. I hope the House will approve of this at an early date so that I can go to the other House before the Budget debate is taken up. No doubt about it; it is a very simple Bill dealing with merely the term of the Press Council and giving life to the Press Council which would have otherwise expired. Do not object to the contents of the Bill. It has been my general objection that Article 123 of the Constitution, which empowers the President to promulgate Ordinances during the recess of Parliament, is a very special power. Therefore, Sir, it is an extraordinary power which has to be exercised with very great caution and care and only in an emergent situation. The First Amendment provides that Congress make no law respecting an establishment of religion or prohibiting its free exercise."
    },
    {
      id: 'ssc-cgl-pytt-7',
      title: 'SSC CGL PYTT - 7',
      difficulty: 'PYTT',
      text: "Is positive thinking an inherent characteristic of a person or can it (69) be developed in one's psyche? The opinions differ in answering this vital question. Some people believe that it can be inherited from parents, and cannot be developed. Others believe that like other qualities it can be developed with proper practice and guidance. Still some others hold the opinion that it is hereditary to some extent but be acquired to some degree. There is also a section of people, who believe that all depends on circumstances or luck. We need to adopt a scientific approach to find an answer to the above question. No one can. get success every time even after making efforts, nor can one fail constantly. Moreover, success has different meaning for different people. For some students, getting 60 per cent marks is success, for others it may not be sufficient. In a competitive examination, success means getting selected, whatever the percentage of marks. As for inheritance theory, since positive attitude is not a physical feature but a mental faculty, it cannot be purely hereditary. It can be developed. Moreover, parents play a major role in developing this quality of a child. A child, who watches his parents working hard, having faith in success through their words, behaviour and body language, is likely to develop a similar attitude. The children of short-tempered, over-cautious and nervous parents may assume similar characteristics when they grow up. Psychologists, therefore, prescribe a code of conduct for parents! behaviour in front of their children. They must exude confidence, self-belief and hope, especially in difficult situation, so that the children emulate these qualities. They must be taught the importance of being positive before, during and after the performance of a task. There is no better education for a child than watching his parents come out of a tough situation by means of earnest endeavours. Such success not only gives more joy but also increases self-confidence."
    },
    {
      id: 'ssc-cgl-pytt-8',
      title: 'SSC CGL PYTT - 8',
      difficulty: 'PYTT',
      text: "In the last few years, thanks to jobs becoming global, the importance of English has increased manifold. It has over the years become an important medium of communication, both at the international and intra- national levels. The importance of spoken English is even more, because here are many cases. Where one knows his subject well, but fails to communicate it properly. The practice of spoken English, therefore, is quite essential. Learning English in a country where it is not a native language, opens a number of opportunities for the Individual. An individual can make strides in the management ladder if he or she can speak English fluently. If your English is poor even though with brilliant business ideas, you may still find yourself languishing at the bottom of the management ladder. Your productivity will drop over a period of time since you will find difficulty in expressing your brilliant ideas. Those who can speak good English will probably usurp your ideas and get the credit for all the hard work you did. Group discussion is one of the ways to test someone's communicative skills generally before the final interview for a job. An English language trainer trains the candidates for group discussions. While training the candidates, the trainer aims at grooming the whole personality etc. He usually organizes number of mock interviews to make the candidates confident and to assess them as where they are lacking in order to fill the gap. Fear of speaking in front of groups is one of the greatest fears people have. Here, the role of a trainer is very crucial who trains the candidates in practices confidence, and how to concentrate on his or her message. The trainer begins with a strategy that includes understanding your purpose and role. Then he makes the candidate team how to structure his material into a meaningful message. English is a West Germanic language in the Indo-European language family, with its earliest forms spoken by the inhabitants of early medieval England"
    },
    {
      id: 'ssc-cgl-pytt-9',
      title: 'SSC CGL PYTT - 9',
      difficulty: 'PYTT',
      text: "It is a little over a year now since I had the honour of addressing this great Assembly. In the course of this year the organization which represents the world community has faced many crises. Among these crises has been the tragic death of the late Secretary General of United Nations, who during the many years of his high office, shaped to some extent the working of this Assembly and enlarged its functions. I would like to pay my tribute and my homage to the memory of the Secretary General. Sir, to you, who occupy now this this high seat of the Secretary-General, I offer my warm welcome of regard and greetings. And I can assure you that we, in common with others, not only welcome you here but offer you our full co- operation. I hope that under your guidance, the United Nations will advance from strength to strength and will serve the cause of the peace of the world and the cause of removing the remnants of foreign domination from various parts of the world. The General Assembly and the Security Council took many steps in the last year or more in regard to these matters. Thereby, enlarged to some extent the functions of the organization. Unfortunately, those steps did not yield the results which we had hoped for. I trust we shall work in future with greater unanimity and effectiveness in carrying out the decisions of the United Nations. In the Congo, the United Nations has undertaken a great responsibility and on the success of that venture depends in many ways the future of the United Nations itself. Therefore, it is of the utmost importance that the work which this organization has undertaken in the Congo should succeed and yield results. All the countries represented here are interested in this vital problem. We in India are a little more interested than some others at the invitation of the United Nations placed some of our resources. The Congo has become the symbol and the touchstone of success for the activities of the United Nations. During the last year, many additions have been made to the membership of the General Assembly."
    }
  ]
};